version: "3.8"  # この「Compose ファイルの書式のバージョン」
services:
  web:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/html
    depends_on:
      - app
  app:
    build: ./php
    volumes:
      - ./src:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/conf.d/php.ini
    depends_on:
      - db
  db:
    build: ./mysql/
    environment:
      MYSQL_DATABASE: webqpp_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/initdb.d/init.sql:/docker-entrypoint-initdb.d/init.sql  #初期処理のフォルダ
      - ./mysql/db:/var/lib/mysql               #ここにデータ永続化するためのファイルが入る